
#.
#Config options for TFMG's machinery
[machines]
	#.
	#.
	#Changes the FE production of large generators.
	#Range: 0.0 ~ 3.4028234663852886E38
	largeGeneratorFEModifier = 4.0
	#.
	#Changes the FE production of small generators.
	#Range: 0.0 ~ 3.4028234663852886E38
	smallGeneratorFEModifier = 0.4000000059604645

#.
#Fine tune the kinetic stats of individual components
[stressValues]

	#.
	#.
	#[in Stress Units]
	#Configure the individual stress impact of mechanical blocks. Note that this cost is doubled for every speed increase it receives
	[stressValues.impact]
		large_aluminum_cogwheel = 0.0
		cast_iron_mechanical_pump = 4.0
		steel_encased_aluminum_cogwheel = 0.0
		heavy_casing_encased_steel_cogwheel = 0.0
		heavy_casing_encased_aluminum_cogwheel = 0.0
		brass_mechanical_pump = 4.0
		heavy_casing_encased_shaft = 0.0
		machine_input = 4.0
		nickel_flywheel = 0.0
		heavy_casing_encased_large_steel_cogwheel = 0.0
		steel_cogwheel = 0.0
		steel_encased_large_aluminum_cogwheel = 0.0
		steel_gearbox = 0.0
		aluminum_mechanical_pump = 4.0
		rotor = 350.0
		steel_flywheel = 0.0
		large_steel_cogwheel = 0.0
		steel_encased_shaft = 0.0
		cast_iron_flywheel = 0.0
		plastic_mechanical_pump = 4.0
		steel_mechanical_pump = 4.0
		generator = 40.0
		lead_flywheel = 0.0
		aluminum_flywheel = 0.0
		heavy_casing_encased_large_aluminum_cogwheel = 0.0
		steel_encased_large_steel_cogwheel = 0.0
		aluminum_cogwheel = 0.0
		steel_encased_steel_cogwheel = 0.0

	#.
	#[in Stress Units]
	#Configure how much stress a source can accommodate for.
	[stressValues.capacity]
		low_grade_fuel_engine = 10.0
		gasoline_engine = 91.0
		lpg_engine = 91.0
		electric_motor = 45.0
		large_radial_engine = 118.0
		diesel_engine = 41.0
		compact_engine = 20.0
		turbine_engine = 91.0
		radial_engine = 95.0

