
[system_time]
	#Synchronize game world time with system time
	sync_to_system_time = false
	#Indicates the rate at which time synchronization with the system occurs, measured in ticks
	#Range: 1 ~ 864000
	sync_to_system_time_rate = 20
	#Controls the offset by which to shift the system time synchronization, must be in 0.5 increments
	#Range: -23.0 ~ 23.0
	sync_to_system_time_offset = 0.0

[arbitrary_time]
	#Specifies the duration in seconds for an in-game day, spanning from the 0th tick to the 12000th
	#Range: 4 ~ 10737360
	day_length_seconds = 1200
	#Specifies the duration in seconds for an in-game night, spanning from the 12000th tick to the 0th
	#Range: 4 ~ 10737360
	night_length_seconds = 1000

[miscellaneous]
	debug = false

