
[general]
	disable_mod = false
	auto_start = false
	space_modules = false
	shadow_text = true
	animations = true
	animationSpeed = 1.0
	fontScale = 1.0
	background_color = 1867534416
	hide_debug_crosshair = false
	hide_sidebar = true
	hide_bossbar = true
	always_show_profiler = false
	always_show_tps = false

[[modules_left]]
	name = "minecraft"
	name_color = 10506797
	value_color = 43520
	enabled = true

	[modules_left.lines]
		minecraft = true

[[modules_left]]
	name = "fps"
	color_high = 5635925
	color_med = 16777045
	color_low = 16733525
	enabled = true

	[modules_left.lines]
		fps = true

[[modules_left]]
	name = "coords"
	name_color = 16733525
	color_x = 16733525
	color_y = 5635925
	color_z = 5636095
	enabled = true

	[modules_left.lines]
		player_coords = true
		block_coords = true
		chunk_relative_coords = true
		chunk_coords = true

[[modules_left]]
	name = "chunks"
	name_color = 43775
	value_color = 16777045
	chunks_enabled_color = 5635925
	chunks_disabled_color = 16733525
	total_chunks_color = 16755200
	enabled = true

	[modules_left.lines]
		chunk_sections = true
		chunk_culling = true
		pending_chunks = true
		pending_uploads = true
		available_buffers = true
		client_chunk_cache = true
		loaded_chunks = true
		loaded_chunks_server = true
		forceloaded_chunks = true
		spawn_chunks = true
		chunk_file = true

[[modules_left]]
	name = "location"
	name_color = 43520
	value_color = 5636095
	enabled = true

	[modules_left.lines]
		dimension = true
		facing = true
		rotation = true
		light = true
		light_server = true
		highest_block = true
		highest_block_server = true
		biome = true
		local_difficulty = true
		day_ticks = true
		days_played = true
		slime_chunk = true

[[modules_right]]
	name = "system"
	name_color = 16755200
	value_color = 5636095
	memory_color_toggle = true
	time_format = "HH:mm:ss"
	enabled = true

	[modules_right.lines]
		time = true
		java_version = true
		memory_usage = true
		allocation_rate = true
		allocated_memory = true
		cpu = true
		display = true
		gpu = true
		gpu_utilization = true
		opengl_version = true
		gpu_driver = true

