#.
#Migrate copycats to Create: Copycats+ when they receive a block update
migrateCopycatsOnBlockUpdate = true
#.
#Migrate copycats to Create: Copycats+ when their block entities are initialized
migrateCopycatsOnInitialize = true

#.
#Enable/disable features. Values on server override clients
[features]
	copycat_vertical_step = false
	six_way_gearbox = true
	item_silo = true
	encased_chain_cogwheel = true
	inverted_clutch = true
	sequenced_pulse_generator = true
	empty_fan_catalyst = true
	parallel_gearbox = true
	freewheel_clutch = true
	shear_pin = true
	inverted_gearshift = true
	centrifugal_clutch = true
	copycat_slab = false
	overstress_clutch = true
	brake = true
	copycat_block = false
	copycat_beam = false
	brass_gearbox = true
	linked_transmitter = true
	bamboo_window = true
	cherry_window = true
	copycat_fence_gate = false
	copycat_stairs = false
	copycat_wall = false
	copycat_board = false
	copycat_fence = false
	#.
	fluid_vessel = true
	large_crank_wheel = true
	crank_wheel = true
	inventory_access_port = true
	inventory_bridge = true

#.
#Enable/disable categories of features. Disabling a category hides all related features. Values on server override clients
[feature_categories]
	#.
	#.
	#All kinetic components, such as gearboxes and crank wheels
	kinetic = true
	#.
	#All redstone components, such as linked transmitter and sequenced pulse generator
	redstone = true
	#.
	#All components related to item and fluid transport
	logistics = true
	#.
	#All copycats (Install Create: Copycats+ to upgrade)
	copycats = true
	#.
	#All building palette blocks
	palette = true

