
#General configuration settings
[client]
	#Show underline on link
	underlineLink = false
	#Enable color on link
	colorLink = false
	#Color of the link
	#Valid colors: 
	#black, dark_blue, dark_green, dark_aqua, dark_red, dark_purple, gold, gray, dark_gray, blue, green, aqua, red, light_purple, yellow, white
	colorName = "blue"

