
[viner]
	#Maximum number of blocks to vein mine
	#Range: > 1
	vineableLimit = 64
	#List of blocks/tags that can be vein mined. Tags must start with '#'
	vineableBlocks = ["#minecraft:ores", "#minecraft:logs", "#minecraft:leaves", "#forge:ores", "minecraft:skulk", "#minecraft:sand"]
	#List of blocks that will not vein mined. This will override blocks from tags in VINEABLE_BLOCKS
	unvineableBlocks = []
	#A 'true' or 'false' field to allow Viner to mine any block.
	vineAll = true
	#(Must have SHAPE_VINE enabled) The number of blocks to mine above the starting block. This value sets how far upwards the tool mines from the starting position. Minimum is 0 (no mining above), and there is no upper limit.
	#Range: > 0
	heightAbove = 1
	#(Must have SHAPE_VINE enabled) The number of blocks to mine below the starting block. This value sets how far downwards the tool mines from the starting position. Minimum is 0 (no mining below), and there is no upper limit.
	#Range: > 0
	heightBelow = 1
	#(Must have SHAPE_VINE enabled) The number of blocks to mine to the left of the starting block. This value sets how far to the left (from the player's perspective) the tool mines. Minimum is 0 (no mining to the left), and there is no upper limit.
	#Range: > 0
	widthLeft = 1
	#(Must have SHAPE_VINE enabled) The number of blocks to mine to the right of the starting block. This value sets how far to the right (from the player's perspective) the tool mines. Minimum is 0 (no mining to the right), and there is no upper limit.
	#Range: > 0
	widthRight = 1

