
[Visuals]
	#This will Enable or Disable the drop shadow effect in the text screen of the Skills Record.
	text_screen_shadow = true
	#This is the background color for the skills record GUI.
	#Allowed Values: DEFAULT, RED, ORANGE, YELLOW, GREEN, BLUE, INDIGO, VIOLET
	background_color = "DEFAULT"
	#This will enable or disable the animations on the skills record GUI.
	animations_mode = true
	#Here you can choose whatever mode you prefer for the bar visibility
	#In the skills record GUI.
	#0: Always on.
	#1: On holding its keybind. "Default Keybind: Shift"
	#2: Disabled.
	#Range: 0 ~ 2
	progress_bar_mode = 0
	#Here you can enable or disable the Mining Skill Card Renderer
	#It's not recommended for now! [WIP]
	msc_renderer = false
	#You can choose when will the challenges panel appears on the screen.
	#Allowed Values: DISABLED, TOP_LEFT, TOP_RIGHT, LEFT, RIGHT, BOTTOM_LEFT, BOTTOM_RIGHT
	challenges_panel_pos = "LEFT"

